### ISSUE TITLE
Allow passing arguments to faker commands

### ISSUE THREAD

**Issue by zbarbuto** [NextFaze/loopback-faker-mixin#1]
Some commands like `faker.random.number` allow specifying a min/max or postcode can have a format specified. Would be good if you could pass these arguments in the config which get.

It doesn't look like `faker.fake` allows for passing these arguments so would have to call the methods directly.

**Comment by paulussup** [comment]
Agreed... Where do you think this logic would be best placed? in model.json or at instantiation?

**Comment by zbarbuto** [comment]
I feel potentially allow the config in model.json to be a property in an object which takes an arg or array of args to be forwarded to the method using `.apply`

```
"properties": {
  "age": {
    "type": "number",
    "faker": {
        "random.number": [1, 100]
    }
  },
  "postcode": {
    "type": "number",
    "faker": {
        "address.zipCode": "xxxx"
    }
  }
}
```

**Comment by paulussup** [comment]
My thoughts were if we do it this way we should also drop the dependence on faker making it more generic
