### ISSUE TITLE
Add moment support

### ISSUE THREAD

**Issue by zbarbuto** [NextFaze/loopback-faker-mixin#6]
The date methods on faker leave a bit to be desired. What would be the thoughts on having a bit more power on the default `Model.faker()` by adding `moment` to `optionalDependencies` and allowing moment methods to be passed in.

Example use case, say you have a `Coupon` model that has a specific `string` format and in a chunk of your tests want a valid coupon out of the box:

```
mixins: {
  Faker: {
     expiry: {
       moment: 'add',
       args: [1, 'week']
       format: 'DD/MM/YYYY'
     }
   }
}
```

Might just be scope creep for something that can just as easily be passed in for every `faker()` call.

Thoughts @paulussup ?

**Comment by paulussup** [comment]
Makes sense. If you have multiple dates that all need to be in the future in a certain order. I could use it in the project I am working on.

**Comment by zbarbuto** [comment]
Have got most of this done to essentially support any module using a source property. Just a few more tests to write and things to experiment with. 

The main troubles were: 1 moment relies very heavily on `this` which can be a bit hectic with all the use of bind and call that exists and 2: unlike faker, moment expects to be constructed first with `moment()` or `moment.Moment` so needed to add a `construct` flag.
